name: build-helm-package
run-name: Build Helm package
on:
  push:
    tags:
      - "v*.*.*"
    paths-ignore:
      - 'helm-chart/**'
    #branches:
    #  - main

jobs:
  build:
    runs-on: "ubuntu-latest"
    outputs:
      release-file: ${{ steps.build-package.outputs.release-file }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GIT_PUSH_TOKEN }}
          ref: main

      - name: Setup Helm
        run: |
          curl https://baltocdn.com/helm/signing.asc | gpg --dearmor | sudo tee /usr/share/keyrings/helm.gpg > /dev/null
          sudo apt-get install apt-transport-https --yes
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/helm.gpg] https://baltocdn.com/helm/stable/debian/ all main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list
          sudo apt-get update
          sudo apt-get install -y helm

      - name: Lint Helm Chart
        run: helm lint .

      - name: Build Helm package
        id: build-package
        run: |
          helm package .
          echo "release-file=$(ls -1 freshrss-*.tgz)" >> $GITHUB_OUTPUT
          echo "release-file=$(ls -1 freshrss-*.tgz)" >> $GITHUB_ENV

      - name: Update Helm Chart repository
        run: |
          cp freshrss-*.tgz helm-chart/
          cd helm-chart
          helm repo index --url http://freshrss-helm.binware.dev/ --merge index.yaml .
          git config --global user.name 'p0l0'
          git config --global user.email '1452110+p0l0@users.noreply.github.com'
          git add .
          git commit -am "Updated Helm repository for ${{env.release-file}}"
          git push

      - name: Cache package
        uses: actions/cache@v3
        with:
          key: ${{env.release-file}}
          path: ${{env.release-file}}

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Cache package
        uses: actions/cache@v3
        with:
          key: ${{needs.build.outputs.release-file}}
          path: |
            ${{needs.build.outputs.release-file}}

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{needs.build.outputs.release-file}}
          token: ${{ secrets.GIT_PUSH_TOKEN }}
